#!/bin/bash
# ═══════════════════════════════════════════════
#  Rename: DataLens → Datorio
#  Run from project root: bash rename-datorio.sh
# ═══════════════════════════════════════════════
set -e

echo "🔄 Renaming DataLens → Datorio..."

# ── 1. Rename Kotlin package directories ──
echo "  [1/7] Renaming package directories..."

# Main sources
if [ -d "backend/src/main/kotlin/com/datalens" ]; then
  mkdir -p backend/src/main/kotlin/com/datorio
  cp -r backend/src/main/kotlin/com/datalens/* backend/src/main/kotlin/com/datorio/
  rm -rf backend/src/main/kotlin/com/datalens
fi

# Test sources
if [ -d "backend/src/test/kotlin/com/datalens" ]; then
  mkdir -p backend/src/test/kotlin/com/datorio
  cp -r backend/src/test/kotlin/com/datalens/* backend/src/test/kotlin/com/datorio/
  rm -rf backend/src/test/kotlin/com/datalens
fi

# Build output (if exists)
if [ -d "backend/build/classes/kotlin/main/com/datalens" ]; then
  rm -rf backend/build
fi

# ── 2. Rename specific files ──
echo "  [2/7] Renaming specific files..."

# DataLensApplication.kt → DatorioApplication.kt
if [ -f "backend/src/main/kotlin/com/datorio/DataLensApplication.kt" ]; then
  mv backend/src/main/kotlin/com/datorio/DataLensApplication.kt \
     backend/src/main/kotlin/com/datorio/DatorioApplication.kt
fi

# DataLensApplicationTests.kt
if [ -f "backend/src/test/kotlin/com/datorio/DataLensApplicationTests.kt" ]; then
  mv backend/src/test/kotlin/com/datorio/DataLensApplicationTests.kt \
     backend/src/test/kotlin/com/datorio/DatorioApplicationTests.kt
fi

# DataLensUserDetailsService.kt
if [ -f "backend/src/main/kotlin/com/datorio/security/DataLensUserDetailsService.kt" ]; then
  mv backend/src/main/kotlin/com/datorio/security/DataLensUserDetailsService.kt \
     backend/src/main/kotlin/com/datorio/security/DatorioUserDetailsService.kt
fi

# ── 3. Replace in all Kotlin files ──
echo "  [3/7] Replacing references in Kotlin files..."

find backend/src -name "*.kt" -exec sed -i \
  -e 's/package com\.datalens/package com.datorio/g' \
  -e 's/import com\.datalens/import com.datorio/g' \
  -e 's/com\.datalens/com.datorio/g' \
  -e 's/DataLensApplication/DatorioApplication/g' \
  -e 's/DataLensUserDetailsService/DatorioUserDetailsService/g' \
  -e 's/DataLens BI/Datorio/g' \
  -e 's/"DataLens"/"Datorio"/g' \
  -e 's/datalens-bi/datorio/g' \
  -e 's/datalens-ds-/datorio-ds-/g' \
  -e 's/noreply@datalens\.local/noreply@datorio.local/g' \
  -e 's/admin@datalens\.local/admin@datorio.local/g' \
  -e 's/Generated by DataLens/Generated by Datorio/g' \
  -e 's/DataLens Report:/Datorio Report:/g' \
  {} +

# Replace @Value config prefixes: datalens. → datorio.
find backend/src -name "*.kt" -exec sed -i \
  -e 's/\${datalens\./\${datorio./g' \
  -e 's/"datalens\./"datorio./g' \
  {} +

# ── 4. Replace in application.yml ──
echo "  [4/7] Replacing references in YAML configs..."

find backend/src -name "application.yml" -exec sed -i \
  -e 's/name: datalens-bi/name: datorio/g' \
  -e 's/DB_NAME:datalens}/DB_NAME:datorio}/g' \
  -e 's/DB_USER:datalens}/DB_USER:datorio}/g' \
  -e 's/DB_PASSWORD:datalens}/DB_PASSWORD:datorio}/g' \
  -e 's/admin@datalens\.local/admin@datorio.local/g' \
  -e 's|postgresql://postgres:5432/datalens|postgresql://postgres:5432/datorio|g' \
  -e 's|postgresql:16:///datalens|postgresql:16:///datorio|g' \
  -e 's/datalens:/datorio:/g' \
  -e 's/com\.datalens/com.datorio/g' \
  {} +

# ── 5. Replace in Gradle files ──
echo "  [5/7] Replacing references in Gradle files..."

# settings.gradle.kts
sed -i 's/datalens-bi/datorio/g' settings.gradle.kts 2>/dev/null || true

# build.gradle.kts (root)
sed -i 's/com\.datalens/com.datorio/g' build.gradle.kts 2>/dev/null || true

# ── 6. Replace in Docker/CI files ──
echo "  [6/7] Replacing references in Docker/CI files..."

# Dockerfile
sed -i \
  -e 's/DataLens BI/Datorio/g' \
  -e 's/DataLens BI Platform/Datorio BI Platform/g' \
  -e 's/addgroup -S datalens/addgroup -S datorio/g' \
  -e 's/adduser -S datalens -G datalens/adduser -S datorio -G datorio/g' \
  -e 's/USER datalens/USER datorio/g' \
  Dockerfile 2>/dev/null || true

# docker-compose.yml
sed -i \
  -e 's/DataLens BI/Datorio/g' \
  -e 's/datalens-bi/datorio/g' \
  -e 's/datalens-postgres/datorio-postgres/g' \
  -e 's/datalens-clickhouse/datorio-clickhouse/g' \
  -e 's/datalens-net/datorio-net/g' \
  -e 's/container_name: datalens/container_name: datorio/g' \
  -e 's/DB_NAME: datalens/DB_NAME: datorio/g' \
  -e 's/DB_USER: datalens/DB_USER: datorio/g' \
  -e 's/POSTGRES_DB: datalens/POSTGRES_DB: datorio/g' \
  -e 's/POSTGRES_USER: datalens/POSTGRES_USER: datorio/g' \
  -e 's/admin@datalens\.local/admin@datorio.local/g' \
  -e 's/pg_isready -U datalens/pg_isready -U datorio/g' \
  -e 's/# ── DataLens/# ── Datorio/g' \
  -e 's/datalens_secret/datorio_secret/g' \
  -e 's/datalens    :/datorio    :/g' \
  -e 's/up -d datalens/up -d datorio/g' \
  -e 's/logs -f datalens/logs -f datorio/g' \
  -e 's/^  datalens:/  datorio:/g' \
  docker-compose.yml 2>/dev/null || true

# .gitlab-ci.yml
if [ -f ".gitlab-ci.yml" ]; then
  sed -i \
    -e 's/datalens/datorio/g' \
    -e 's/DataLens/Datorio/g' \
    .gitlab-ci.yml
fi

# .github/workflows/ci.yml
if [ -f ".github/workflows/ci.yml" ]; then
  sed -i \
    -e 's/datalens/datorio/g' \
    -e 's/DataLens/Datorio/g' \
    .github/workflows/ci.yml
fi

# ── 7. Replace in Frontend files ──
echo "  [7/7] Replacing references in Frontend files..."

# package.json
sed -i 's/"datalens-ui"/"datorio-ui"/g' frontend/package.json 2>/dev/null || true

# index.html
sed -i 's/DataLens BI/Datorio/g' frontend/index.html 2>/dev/null || true

# LoginPage.tsx
find frontend/src -name "LoginPage.tsx" -exec sed -i \
  -e 's/DataLens BI/Datorio/g' \
  -e 's/DataLens/Datorio/g' \
  {} + 2>/dev/null || true

# Sidebar.tsx
find frontend/src -name "Sidebar.tsx" -exec sed -i \
  -e 's/DataLens/Datorio/g' \
  {} + 2>/dev/null || true

# Email service references in frontend (if any)
find frontend/src -name "*.tsx" -name "*.ts" -exec sed -i \
  -e 's/DataLens/Datorio/g' \
  {} + 2>/dev/null || true

# README
sed -i \
  -e 's/DataLens BI/Datorio/g' \
  -e 's/DataLens/Datorio/g' \
  -e 's/datalens-bi/datorio/g' \
  -e 's/datalens/datorio/g' \
  README.md 2>/dev/null || true

echo ""
echo "✅ Rename complete! Verify with:"
echo "   grep -r 'datalens\|DataLens' --include='*.kt' --include='*.yml' --include='*.tsx' --include='*.ts' --include='*.kts' --include='*.json' --include='*.html' . | grep -v node_modules | grep -v .git | grep -v build/"
echo ""
echo "⚠️  Manual steps:"
echo "   1. Update PostgreSQL database name/user if needed (DB_NAME, DB_USER env vars)"
echo "   2. Update .env file if you have one"
echo "   3. Drop and recreate Docker volumes if changing DB name:"
echo "      docker-compose down -v && docker-compose up -d"
echo ""
echo "📦 Commit:"
echo "   git add -A"
echo "   git commit -m 'refactor: rename DataLens → Datorio'"
