package com.datorio.service

import com.datorio.model.dto.*
import com.datorio.repository.ReportRepository
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service
import java.util.Properties
import jakarta.mail.*
import jakarta.mail.internet.*

@Service
class EmailService(
    private val exportService: ExportService,
    private val reportRepo: ReportRepository
) {
    private val log = LoggerFactory.getLogger(javaClass)

    @Value("\${datorio.email.enabled:false}")
    private var emailEnabled: Boolean = false

    @Value("\${datorio.email.smtp-host:}")
    private var smtpHost: String = ""

    @Value("\${datorio.email.smtp-port:587}")
    private var smtpPort: Int = 587

    @Value("\${datorio.email.username:}")
    private var smtpUsername: String = ""

    @Value("\${datorio.email.password:}")
    private var smtpPassword: String = ""

    @Value("\${datorio.email.from:noreply@datorio.local}")
    private var fromAddress: String = "noreply@datorio.local"

    @Value("\${datorio.email.use-tls:true}")
    private var useTls: Boolean = true

    /**
     * Send a report export to recipients via email.
     */
    fun sendReportEmail(request: EmailDeliveryRequest, username: String): EmailDeliveryResponse {
        if (!emailEnabled) {
            log.warn("Email delivery is disabled. Enable with datalens.email.enabled=true")
            return EmailDeliveryResponse(
                success = false,
                recipientCount = 0,
                message = "Email delivery is not configured. Set datalens.email.enabled=true and configure SMTP."
            )
        }

        if (request.recipients.isEmpty()) {
            return EmailDeliveryResponse(false, 0, "No recipients specified")
        }

        val report = reportRepo.findById(request.reportId)
            .orElseThrow { IllegalArgumentException("Report not found: ${request.reportId}") }

        // Export the report
        val exportRequest = ExportRequest(
            format = request.format,
            parameters = request.parameters
        )
        val (fileBytes, filename) = exportService.exportReport(request.reportId, exportRequest, username)

        val contentType = when (request.format.uppercase()) {
            "CSV" -> "text/csv"
            "EXCEL", "XLSX" -> "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            "PDF" -> "application/pdf"
            else -> "application/octet-stream"
        }

        val subject = request.subject ?: "Datorio Report: ${report.name}"
        val body = request.body ?: "Please find attached the report \"${report.name}\".\n\nGenerated by Datorio."

        return try {
            val session = createMailSession()

            for (recipient in request.recipients) {
                val message = MimeMessage(session).apply {
                    setFrom(InternetAddress(fromAddress, "Datorio"))
                    setRecipient(Message.RecipientType.TO, InternetAddress(recipient))
                    setSubject(subject)

                    // Multipart: text body + attachment
                    val multipart = MimeMultipart()

                    // Body
                    val bodyPart = MimeBodyPart()
                    bodyPart.setText(body, "UTF-8")
                    multipart.addBodyPart(bodyPart)

                    // Attachment
                    val attachPart = MimeBodyPart()
                    attachPart.setContent(fileBytes, contentType)
                    attachPart.fileName = filename
                    multipart.addBodyPart(attachPart)

                    setContent(multipart)
                }

                Transport.send(message)
                log.info("Sent report '{}' to {}", report.name, recipient)
            }

            EmailDeliveryResponse(
                success = true,
                recipientCount = request.recipients.size,
                message = "Report sent to ${request.recipients.size} recipient(s)"
            )
        } catch (e: Exception) {
            log.error("Failed to send email: {}", e.message)
            EmailDeliveryResponse(
                success = false,
                recipientCount = 0,
                message = "Email failed: ${e.message}"
            )
        }
    }

    private fun createMailSession(): Session {
        val props = Properties().apply {
            put("mail.smtp.host", smtpHost)
            put("mail.smtp.port", smtpPort.toString())
            put("mail.smtp.auth", (smtpUsername.isNotBlank()).toString())
            if (useTls) {
                put("mail.smtp.starttls.enable", "true")
            }
        }

        return if (smtpUsername.isNotBlank()) {
            Session.getInstance(props, object : Authenticator() {
                override fun getPasswordAuthentication() =
                    PasswordAuthentication(smtpUsername, smtpPassword)
            })
        } else {
            Session.getInstance(props)
        }
    }
}
